apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoramento
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/FriedrichMatheus/k8s_.git
    targetRevision: HEAD
    path: monitoramento
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoramento
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      